name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Configure npm
        run: |
          npm config set registry https://registry.npmjs.org/
          npm config set fetch-retry-mintimeout 20000
          npm config set fetch-retry-maxtimeout 120000
          npm config set fetch-retries 5
      
      - name: Install dependencies with retry
        run: |
          for i in {1..3}; do
            echo "Attempt $i to install dependencies..."
            if npm ci --no-audit --no-fund; then
              echo "Dependencies installed successfully!"
              break
            else
              echo "Attempt $i failed. Waiting 30 seconds before retry..."
              sleep 30
            fi
          done
          npm rebuild
      
      - name: Build
        run: npm run generate
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .output/public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
